### ISSUE TITLE
running cargo bloat on itself fails

### ISSUE THREAD

**Issue by matthiaskrgr** [RazrFalcon/cargo-bloat#40]
repo  @ 74f19773beb90a5f5c1f5ea374536a46636963cb

`RUST_BACKTRACE=Full  RUSTC_WRAPPER="" ./target/debug/cargo-bloat bloat`
````
Compiling ...
thread 'main' panicked at 'slice index starts at 102607 but ends at 496', src/libcore/slice/mod.rs:2561:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2561
  11: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libcore/slice/mod.rs:2730
  12: <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libcore/slice/mod.rs:2813
  13: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libcore/slice/mod.rs:2538
  14: cargo_bloat::parser::parse_null_string
             at src/parser.rs:158
  15: cargo_bloat::elf64::parse_symbols
             at src/elf64.rs:112
  16: cargo_bloat::elf64::parse_section_header
             at src/elf64.rs:82
  17: cargo_bloat::elf64::parse
             at src/elf64.rs:34
  18: cargo_bloat::collect_self_data
             at src/main.rs:735
  19: cargo_bloat::process_crate
             at src/main.rs:594
  20: cargo_bloat::main
             at src/main.rs:173
  21: std::rt::lang_start::{{closure}}
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/rt.rs:64
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  25: std::panicking::try
             at src/libstd/panicking.rs:275
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  28: std::rt::lang_start
             at /rustc/311376d30dc1cfa622142a9f50317b1e0cb4608a/src/libstd/rt.rs:64
  29: main
  30: __libc_start_main
  31: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
````

**Comment by RazrFalcon** [comment]
Works for me. Maybe you have a different Rust version, which produce a different output.

Can you send me this binary?

**Comment by matthiaskrgr** [comment]
I'm using rustc 1.38.0-nightly (311376d30 2019-07-18)

**Comment by RazrFalcon** [comment]
Works fine with `rustc 1.38.0-nightly (273f42b59 2019-07-21)`.

**Comment by matthiaskrgr** [comment]
Ok, guess I'll check back when I can update again (currently stuck on ..07-18 since tools are broken in more recent versions).

**Comment by RazrFalcon** [comment]
Can you send me a bin file?

**Comment by RazrFalcon** [comment]
Should be fixed now. Please confirm.

**Comment by matthiaskrgr** [comment]
Looks good to me, thanks :)

**Comment by RazrFalcon** [comment]
Glad to hear that.
