### ISSUE TITLE
crash on a nostd project

### ISSUE THREAD

**Issue by almindor** [RazrFalcon/cargo-bloat#41]
cargo-bloat currently crashes for me on a nostd (embedded) project.

Also NOTE: it's in a workspace

Backtrace:

```
$ RUST_BACKTRACE=1 cargo-bloat bloat -n 10 --release
Compiling ...
thread 'main' panicked at 'slice index starts at 1461 but ends at 214', src/libcore/slice/mod.rs:2575:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2575
   9: cargo_bloat::parser::parse_null_string
  10: cargo_bloat::elf32::parse
  11: cargo_bloat::process_crate
  12: cargo_bloat::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  16: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  17: main
  18: __libc_start_main
  19: _start
```

**Comment by RazrFalcon** [comment]
Can you send me this binary?

**Comment by almindor** [comment]
Here's the binary zipped. NOTE: it's target architecture is `riscv32imac-unknown-none-elf`

[z.zip](https://github.com/RazrFalcon/cargo-bloat/files/3417898/z.zip)

**Comment by RazrFalcon** [comment]
Should be fixed now. Please confirm.
